# fly.toml file generated for dawn-flower-8979 on 2023-04-04T14:30:10+01:00

app = "dawn-flower-8979"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "jnb"
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_NAME="MoreAdvice"
  APP_KEY="base64:t5xNGiQ+VXephTEborVzZqAjdemRzXwUDxUvU9ts3wo="
  APP_DEBUG="true"
  APP_URL="https://dawn-flower-8979.fly.dev/"
  LOG_DEPRECATIONS_CHANNEL="null"
  DB_CONNECTION="sqlite"
  BROADCAST_DRIVER="log"
  CACHE_DRIVER="file"
  FILESYSTEM_DISK="local"
  QUEUE_CONNECTION="sync"
  SESSION_DRIVER="cookie"
  SESSION_LIFETIME="120"
  SESSION_SECURE_COOKIE="true"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
